# 工作流的名称
name: Deploy to GitHub Pages

# 触发工作流的事件
on:
  push:
    branches:
      # 当有代码推送到 main 或 development 分支时，触发此工作流
      - main
      - development

# 定义一系列任务（jobs）
jobs:
  # 部署任务
  build-and-deploy:
    # 运行此任务的操作系统环境
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 确保拉取完整历史，这对于部署到 gh-pages 很重要
          fetch-depth: 0

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. 安装项目依赖
      - name: Install dependencies
        run: pnpm install

      # 5. 编译项目
      - name: Build project
        run: pnpm build

      # 6. 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 使用 GitHub 提供的 Token 进行认证
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 指定要部署的文件夹，通常是编译后的 dist 目录
          publish_dir: ./dist
          # 强制推送，覆盖 gh-pages 分支的现有内容
          force_orphan: true
          # 部署时使用的提交信息
          commit_message: "feat: deploy to github pages"
